// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvYrZHYjUGKukB8tqtRCUNwy5G2wPsi0k',
    appId: '1:15994186305:web:1af347a708c80c36a974c0',
    messagingSenderId: '15994186305',
    projectId: 'us-building-client',
    authDomain: 'us-building-client.firebaseapp.com',
    storageBucket: 'us-building-client.appspot.com',
    measurementId: 'G-L7FJ4JV4B9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsKJ8SzFR6bxsFVIeCw0T2MfycRfh10Sk',
    appId: '1:15994186305:android:90aee5683811fe3ba974c0',
    messagingSenderId: '15994186305',
    projectId: 'us-building-client',
    storageBucket: 'us-building-client.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5lvUErgGkD6db557e8xO403ylyh0FSFs',
    appId: '1:15994186305:ios:28f832ccceeced54a974c0',
    messagingSenderId: '15994186305',
    projectId: 'us-building-client',
    storageBucket: 'us-building-client.appspot.com',
    iosBundleId: 'com.keri.usBuildingClient',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD5lvUErgGkD6db557e8xO403ylyh0FSFs',
    appId: '1:15994186305:ios:7aa440cac5c68065a974c0',
    messagingSenderId: '15994186305',
    projectId: 'us-building-client',
    storageBucket: 'us-building-client.appspot.com',
    iosBundleId: 'com.keri.usBuildingClient.RunnerTests',
  );
}
